language: node_js
node_js:
  - 8
  - 6

jobs:
  include:
    - stage: npm release
      node_js: lts/*
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
