language: node_js

node_js: 6

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: npm release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
