language: node_js

jobs:
  include:
    - stage: npm release
      node_js: 8
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
