language: node_js
cache:
  directories:
  - $HOME/.npm
jobs:
  include:
    - stage: npm release
      node_js: 8
      if: branch = master
      script: skip
      after_script: skip
      deploy:
        provider: script
        script: npx semantic-release
